### ISSUE TITLE
expected string or buffer

### ISSUE THREAD

**Issue by asmplease** [quadrismegistus/prosodic#11]
trying to parse this line .
`t = p.Text("""As in a dark beginning of all things,
A mute featureless semblance of the Unknown
Repeating for ever the unconscious act,
Prolonging for ever the unseeing will,
Cradled the cosmic drowse of ignorant Force
Whose moved creative slumber kindles the suns
And carries our lives in its somnambulist whirl.""")`
I get the following error '**TypeError: expected string or buffer**'

**Comment by quadrismegistus** [comment]
Hi, do you still get this error? I don't. It may have been solved in the transition to Python 3?

**Comment by asmplease** [comment]
Yes the issue is solved now.
Thanks for your help.
