### ISSUE TITLE
Example output files

### ISSUE THREAD

**Issue by timmahrt** [quadrismegistus/prosodic#13]
Can you provide some example (non-trivial) output files?  Such as the long-form poem in the readme.  Even better if you can link/directly load the file in the readme.

**Comment by quadrismegistus** [comment]
Sorry to take an eternity to reply.

Here's the three data files produced by "/stats all" in prosodic for Shakespeare sonnet #1: https://www.dropbox.com/sh/q13jsvsxem5lvdw/AACE0VSc0hL4UfEJDhWpFs5oa?dl=0

Also take a look at (an experimental) web interface: http://prosodic.stanford.edu for a visual look at the data.
