### ISSUE TITLE
Error on entering string: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by BrianSantoso** [quadrismegistus/prosodic#15]
>> [0.0s] prosodic:en$ "test"
Traceback (most recent call last):
  File "prosodic.py", line 197, in <module>
    text=input(msg).strip().decode('utf-8',errors='ignore')
AttributeError: 'str' object has no attribute 'decode'

When running py prosodic.py and typing anything, the above error occurs (Windows 10, Python 3.8.0)

**Comment by ethan-ou** [comment]
+1 It appears that if you remove all mentions of .decode() from prosodic.py, the error goes away. I think it's because strings are handled differently in Python 3, which means they don't need to be decoded. Not sure however whether this will affect compatibility for Python 2.

**Comment by quadrismegistus** [comment]
Thanks guys! This should be fixed now
