### ISSUE TITLE
Have you considered a non-command line interface for use in program libraries?

### ISSUE THREAD

**Issue by harrisj** [quadrismegistus/prosodic#2]
This is really cool, but I want to scan bulk-lines of text for iambic pentameter and there doesn't seem to be a convenient way to do this. I can hack this by importing and calling functions, but I was wondering if you considered creating an interface suitable for importing into other projects and easily called for commands?

**Comment by quadrismegistus** [comment]
The Python pip package is now available at pip install prosodic
