### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by LC740** [quadrismegistus/prosodic#21]
Hi,
I've just installed prosodic on a lubuntu with python3 (but I tried also with python 2.7) and I renamed config_default.py to config.py
But every time I run "prosodic", I get this:

_File "/usr/local/bin/prosodic", line 5
  cmd = f'python {path_to_prosodic_py} {argstr}'
                                                                           ^
SyntaxError: invalid syntax_

Is there anything I can do to fix it?
Note: the ^ is under the ' at the end of {argstr}'

**Comment by quadrismegistus** [comment]
I think that f' x... {var} x' string functionality was added in python 3.6. It's not really needed in that file though. I just edited it in the git repo. Can you try reinstalling? If you used pip to install, you can run:

```
pip install git+https://github.com/quadrismegistus/prosodic
```

**Comment by LC740** [comment]
I uninstalled and reinstsalled prosodic (I used pip both times). This is the result:

Traceback (most recent call last):
  File "/usr/local/bin/prosodic", line 5, in <module>
     import prosodic
  File "/usr/local/lib/python2.7/dist-packages/prosodic/__init__.py", line 2, in <module>
     from .prosodic import *
  File "/usr/local/lib/python2.7/dist-packages/prosodic/prosodic.py", line 136
     cmd='{dir_get_deps} "{dir_nlp_data}"'
                                                              ^
SyntaxError: invalid syntax

**Comment by quadrismegistus** [comment]
I see, it looks like prosodic needs 3.6+ now, since those f"" string declarations are more pervasive. Could you try upgrading your python to 3.6+, and making sure your 'python' executable points to it? I recommend miniconda for python version management, fwiw.

**Comment by LC740** [comment]
I upgraded python to 3.6.9 and linked python to its executable. I got another error:

_Traceback (most recent call last):
File "/usr/local/bin/prosodic", line 5, in [module]
import prosodic
ModuleNotFoundError: No module named 'prosodic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/bin/prosodic", line 13, in [module]
import prosodic
ModuleNotFoundError: No module named 'prosodic'_

**Comment by quadrismegistus** [comment]
Hm, is your pip pointing to a different python than your python?

```which python
which pip```
?

Maybe try:
```
pip uninstall prosodic
python -m pip install git+https://github.com/quadrismegistus/prosodic
```
?

Otherwise, it's a bug and I'll look into it.

**Comment by LC740** [comment]
"python3 -m pip install git+https://github.com/quadrismegistus/prosodic" fixed the problem. Thanks!

**Comment by quadrismegistus** [comment]
Great! Let me know if you have any other Qs. And keep in mind the web interface @ https://prosodic.stanford.edu for quick spot checking of lines or short texts.
