### ISSUE TITLE
Can't install, prosodic/tagged_samples is missing

### ISSUE THREAD

**Issue by polm** [quadrismegistus/prosodic#23]
I'm on Arch Linux using Python 3.9 and can't install prosodic. I get an error that `prosodic/tagged_samples` is missing while the wheel is being built. 

Maybe it needs to be added to MANIFEST.in? 

At first I thought this might be related to #20, but the levenshtein package installs without issue for me.

**Comment by quadrismegistus** [comment]
Ok, I've played around with pypi and I think it should be working now?

```pip install -U prosodic```

should install 1.3.12 (or higher), which should be able to copy both tagged_samples and corpora now?

cc @tnhaider

**Comment by polm** [comment]
It worked, thanks!
