### ISSUE TITLE
Syllable feature('prom.stress') not the same as capitalization in parse?

### ISSUE THREAD

**Issue by tnhaider** [quadrismegistus/prosodic#24]
Hi, 

I noticed something odd. 

I am parsing the en.alliteration.txt with this code:
```
import sys
import prosodic as p
#t = p.Text('Shall I compare thee')
t = p.Text('../corpora/corppoetry_en/en.alliteration.txt')
t.parse()
for p in t.bestParses():
        print('PARSE: ', p)
        meter_list = []
        if p is not None:
                ws = p.words()
                print('WORDS: ', ws)
                for w in ws:
                        ss = w.syllables()
                        print('SYLLABLES:', ss)
                        for s in ss:
                                f = s.feature('prom.stress')
                                print(f)
                                if f < .5:
                                        meter_list.append('-')
                                else:
                                        meter_list.append('+')
        print(meter_list)
```

But it seems that in the output, the character capitalization of the /PARSE does not match the assigned prominence values in the syllable features. See for example the values of 'THE' and 'BLES'.
```
PARSE:  from|THE|o|RI|gi.nal|COM|mon.ger|MA|nic|LANGUAG|e
WORDS:  [<Word.from> [fr\u028cm], <Word.the> [ð\u0259], <Word.original> [\u025b\u02d0.'\u026a.\u02a4\u0259.n\u0259l], <Word.common> ['k\u0251.m\u0259n], <Word.germanic> [\u02a4\u025b\u02d0.'mæ.n\u026ak], <Word.language> ['læ\u014b.gw\u0259\u02a4]]
SYLLABLES: [<Syllable.from> [fr\u028cm]]
0.0
SYLLABLES: [<Syllable.the> [ð\u0259]]
0.0
SYLLABLES: [<Syllable.o> [\u025b\u02d0], <Syllable.ri> ['\u026a], <Syllable.gi> [\u02a4\u0259], <Syllable.nal> [n\u0259l]]
0.0
1.0
0.0
0.0
SYLLABLES: [<Syllable.com> ['k\u0251], <Syllable.mon> [m\u0259n]]
1.0
0.0
SYLLABLES: [<Syllable.Ger> [\u02a4\u025b\u02d0], <Syllable.ma> ['mæ], <Syllable.nic> [n\u026ak]]
0.0
1.0
0.0
SYLLABLES: [<Syllable.languag> ['læ\u014b], <Syllable.e> [gw\u0259\u02a4]]
1.0
0.0
['-', '-', '-', '+', '-', '-', '+', '-', '-', '+', '-', '+', '-']
PARSE:  MA|ny|STRESSED.SYL|la|BLES|were|LOST
WORDS:  [<Word.many> ['m\u025b.ni\u02d0], <Word.stressed> ['str\u025bst], <Word.syllables> ['s\u026a.l\u0259.b\u0259lz], <Word.were> [w\u025b\u02d0], <Word.lost> ['l\u0254\u02d0st]]
SYLLABLES: [<Syllable.ma> ['m\u025b], <Syllable.ny> [ni\u02d0]]
1.0
0.0
SYLLABLES: [<Syllable.stressed> ['str\u025bst]]
1.0
SYLLABLES: [<Syllable.syl> ['s\u026a], <Syllable.la> [l\u0259], <Syllable.bles> [b\u0259lz]]
1.0
0.0
0.0
SYLLABLES: [<Syllable.were> [w\u025b\u02d0]]
0.0
SYLLABLES: [<Syllable.lost> ['l\u0254\u02d0st]]
1.0
['+', '-', '+', '+', '-', '-', '-', '+']
```

My bet is that the capitalization values of the /parse are correct, but the syllable feature goes by the CMU lexicon?

**Comment by quadrismegistus** [comment]
> My bet is that the capitalization values of the /parse are correct, but the syllable feature goes by the CMU lexicon?

Yes. Capitalization reflects the best-fitting metrical prominence, whereas [prom.stress] reflects the actual phonological stress of the word. When these diverge there should be a stress violation (stress.w=>-p or stress.s=>-u).

Also bear in mind that some words have multiple possible [prom.stress] assignments (into has an entry for PU and UP [primary stress / unstressed]); the meter will use whichever one works better. I'm not sure when you grab the .words() or .syllables() from the parse object that it uses the entry which the parse used, but it should.

**Comment by tnhaider** [comment]
Ok, I do have another question, I think.

Right now, I am taking the capitalization values and compare line by line and syllable by syllabe against my goldstandard.
This is the outcome:
```
                Total    Correct    Accuracy
Lines        1212     477         0.3935643564356436
Syllables  8388     7102       0.8466857415355269
```
I often notice that some syllables are conflated. 
Like here 'so.much':
`I|have|IT|in|ME|so.much|NEA|rer|HOME`
Or here TWEEN.STARS or NO.HU:
`be|TWEEN.STARS|on|STARS|where|NO.HU|man|RACE|is`
I am treating these as separate syllables and hence might have a different contextual annotation.
I suspect this is the source for some error.
Is there a way to change this?

Best,
T.

**Comment by quadrismegistus** [comment]
Yep! This is 'resolution' where two syllables are squeezed into one metrical position. It makes more sense for weak positions ("in.the", "of.the", etc), though some people think it can happen in strong positions too (e.g. in Hopkins' form of "sprung rhythm").

To discourage them you'll have to change the meter (copy one of the .py files in ~/prosodic_data/meter, rename it, and edit file):
* To disallow 2 syllables in strong positions entirely by setting maxS=1 instead of maxS=2 (to do same on weak positions, set maxW=1)
* To discourage resolution by upping the constraint weight for the constraint 'footmin-f-resolution', which only allows two function words to squeeze into a single position (like "of.the", etc)

Let me know if that works?
peace
Ryan

**Comment by tnhaider** [comment]
Ehm, no, sorry, I'm not sure what's happening here. 

I have files in `/meters
I changed the values of maxS and maxW in default_english.py, meter_ryan.py and meter_ryan_categorical.py
It still parses with 2
```
>> no meter specified. defaulting to this meter:
<<Meter
	ID: default_english
	Name: Ryan's Meter
	Constraints: 
		[*footmin-w-resolution/1] [*footmin-f-resolution/1]
		[*strength.w=>-p/1]
		[*stress.s=>-u/1] [*stress.w=>-p/1]
	MaxS, MaxW: 2, 2
	Allow heavy syllable split across two positions: False
>>
text                                                        	parse                                                       	meter	num_parses	num_viols	score_viols	[*footmin-f-resolution]	[*footmin-w-resolution]	[*strength.w=>-p]	[*stress.s=>-u]	[*stress.w=>-p]
To scare myself with my own desert places.                  	to|SCARE|my|SELF|with.my|OWN.DE|sert|PLA|ces                	wswswwsswsw	5	2	2	0	0	1	0	1
```

**Comment by quadrismegistus** [comment]
Hm. If you specify the meter when you run .parse(), does that help?

```python
import prosodic as p
t=p.Text("shall i compare these to a summers day")
t.parse(meter="iambic_pentameter")
```

**Comment by tnhaider** [comment]
Not sure how that would help, because the dataset contains a variety of different meters/measures. 
In fact, if I specify meter='iambic_pentameter', the results are worse.
```
1212 448 0.3696369636963696
8408 6743 0.8019743101807802
```
I also suspect some error stems from wrong syllabification.

**Comment by quadrismegistus** [comment]
Yeah, I wouldn't use iambic_pentameter, just an example of how to specify meter.

I would try these constraints:
```
maxS=1
maxW=2

Cs['strength.w=>-p']=2   # this is the worst violation, so you could give it a higher weight
Cs['stress.s=>-u']=1
Cs['stress.w=>-p']=1
Cs['footmin-w-resolution']=1
Cs['footmin-f-resolution']=1
```

Syllabification is also a problem, you're right. espeak is inaccurate a lot of the time, so when the word isn't in CMU the quality definitely degrades.

**Comment by tnhaider** [comment]
Ok.
But I'm still not sure how to incorporate these constraints.
My directory looks like this:
```
[prosodic]$ ls *
LICENSE.md  MANIFEST.in  README.md  requirements.txt  setup.py

bin:
prosodic

corpora:
corppoetry_en  corppoetry_fi  epg64

meters:
default_english.py         kiparskyhanson_shakespeare.py      prose_rhythm_iambic.py
iambic_pentameter2.py      litlab.py                          prose_rhythm_iambic_violable.py
iambic_pentameter3.py      meter_arto.py                      strength_and_resolution.py
iambic_pentameter.py       meter_ryan_categorical.py          strength_only.py
__init__.py                meter_ryan.py
kiparskyhanson_hopkins.py  prose_rhythm_iambic_inviolable.py

metricaltree:
deptree.py  get-deps.sh  __init__.py  metricaltree.py  README.md  test.py

notebooks:
cookbook.py  metrical_parsing.ipynb

prosodic:
config.py  dicts  eval_prosodic.py  __init__.py  lib  prosodic.py  __pycache__

tagged_samples:
tagged-sample-litlab-2016.evaluated.meter=kiparskyhanson_shakespeare.txt
tagged-sample-litlab-2016.evaluated.meter=litlab.txt
tagged-sample-litlab-2016.evaluated.meter=meter_ryan.txt
tagged-sample-litlab-2016.evaluated.meter=prose_rhythm_iambic.txt
tagged-sample-litlab-2016.evaluated.ot.meter=kiparskyhanson_shakespeare.txt
tagged-sample-litlab-2016.evaluated.ot.meter=litlab.txt
tagged-sample-litlab-2016.evaluated.ot.meter=meter_ryan.txt
tagged-sample-litlab-2016.evaluated.ot.meter=prose_rhythm_iambic.txt
tagged-sample-litlab-2016.txt

tests:
test_unicode.py

```

**Comment by quadrismegistus** [comment]
Do you also have a ```prosodic_data/meters``` directory in your home folder? That may be where the meters are being pulled from these days.

**Comment by tnhaider** [comment]
No, this is the latest pull. That dir is not there.

prosodic.py says this:
```
#default_dir_prosodic_home = os.path.abspath(os.path.expanduser('~/prosodic_data'))
dir_prosodic_home = config.get('path_prosodic_data')
dir_dicts = config.get('path_dicts', os.path.join(dir_prosodic, 'dicts'))
dir_meters = config.get('path_meters', os.path.join(dir_prosodic_home, 'meters'))
dir_results = config.get('path_results', os.path.join(dir_prosodic_home, 'results'))
dir_tagged = config.get('path_tagged_samples', os.path.join(dir_prosodic_home, 'tagged_samples'))
dir_corpus = config.get('path_corpora', os.path.join(dir_prosodic_home, 'corpora'))
dir_nlp_data = config.get('path_nlp_data', os.path.join(dir_prosodic_home, 'nlp_libraries'))

config['meters']=loadMeters(dir_meters,config)
METER=config['meter']=config['meters'][config['meter']] if 'meter' in config and config['meter'] else None
```
And config.py says this:
```
# Relative paths are relative to dir_prosodic_home, which defauls to ~/prosodic_data
# and which can be changed by editing the hidden variable ~/.path_prosodic_data

path_corpora = 'corpora'
path_meters = 'meters'
path_results = 'results'
path_tagged_samples = 'tagged_samples'
path_nlp_data = 'nlp_libraries'


############################################
# METRICAL PARSING
#
# Set the Meter ID: the filename to its configuration file
# in the "meters" subdirectory, e.g. "kiparskyhanson_shakespeare"
# (omit the .py from the filename).
#
meter = 'meter_ryan'
#
# If no Meter ID is provided, PROSODIC will ask you to set the meter
# in its interactive mode. As a python module, you will have to
# create the meter first and pass it to the Text object to parse.
#
# meter = 'meter_arto'
############################################
```

**Comment by quadrismegistus** [comment]
Hm, what if you try installing the pip version now? Unless you've edited the git version code. I think the pip installation process should create the prosodic_data folder.

**Comment by tnhaider** [comment]
But shouldn't it also work like this? 

Maybe it just pulls something from the cache? 
Can I update loading the meter config somehow?

**Comment by quadrismegistus** [comment]
Maybe add ```print(dir_meters)``` in prosodic.py just to see where it's pointing to?

And if you edit one of the existing meters the changes don't show up? Strange, definitely a bug if so.

**Comment by tnhaider** [comment]
Yap, that goes straight to my 
`DIR METERS: /home/thomas.haider/prosodic_data/meters`
which is in a totally different place.

**Comment by tnhaider** [comment]
Ok, I did a quickfix by specifying the absolute path. 
Unfortunately, maxS=1 and maxW=1 also leads to worse results than 2, 2.
(line accuracy is slightly better, but syllable accuracy worse)

```
1212 487 0.4018151815181518
8388 6792 0.8097281831187411
```
I'll try the constraints you suggested.

**Comment by quadrismegistus** [comment]
and which doesn't currently exist I take it?

What happens if you run
```python
import prosodic as p
p.configure_home_dir()
```
? That runs the function which is triggered by pip installation.

**Comment by quadrismegistus** [comment]
> Ok, I did a quickfix by specifying the absolute path.
> Unfortunately, maxS=1 and maxW=1 also leads to worse results than 2, 2.
> (line accuracy is slightly better, but syllable accuracy worse)

Try maxS=1 but maxW=2 ?

**Comment by tnhaider** [comment]
Yap, that helps.
```
1212 535 0.4414191419141914
8388 7114 0.8481163567000477
```

**Comment by quadrismegistus** [comment]
Nice! 85% syllables correct ain't bad. Human to human agreement when I and another grad student both parsed the same poems was only around ~94%.

**Comment by tnhaider** [comment]
Haha, my approach gets me into the high 90s for syllables and into the 80s for lines. 

Our human agreement was also in the high 90s (for binary syllable stress at least).

But it's good that we evaluated this, so I can better argue that there is a point in making corpus driven neural models.

**Comment by tnhaider** [comment]
Thanks for all your help!

**Comment by tnhaider** [comment]
But admittedly, this direct comparison is also a bit unfair, since my own syllabification also makes mistakes (that is currently not reflected in the final evaluation).

**Comment by quadrismegistus** [comment]
> But it's good that we evaluated this, so I can better argue that there is a point in making corpus driven neural models.

Absolutely. Prosodic is an extremely naive rule-based model: it doesn't even take into account the context of the whole poem, much less an author or corpus! Excited to read more about the results of your work. peace

**Comment by tnhaider** [comment]
If I exclude lines with the wrong length (in syllables) from the evaluation, this is the outcome:
```
881 535 0.6072644721906924
7124 6367 0.8937394722066255
```
Well, the numbers look better, but we also find that almost 1/3 of lines have the wrong length.
