### ISSUE TITLE
Unable to run app

### ISSUE THREAD

**Issue by sylveawong** [quadrismegistus/prosodic#61]
I went through the installation steps, and it says to run this command: 

```
pip install git+https://github.com/quadrismegistus/prosodic@develop
```

It looks like the `develop` branch no longer exists, so that doesn't work. I tried: 

```
pip install git+https://github.com/quadrismegistus/prosodic
```

And that seems to work correctly and I see the `prosodic` and `prosodic-2.0.0.dev1.dist-info` folders in my python site-packages. But when I run `prosodic` I get this: 

```
zsh: command not found: prosodic
```

Any ideas? Should I be installing it from a different branch? Or running that command from somewhere specific? 

Thanks!

**Comment by quadrismegistus** [comment]
Hi there, would it be possible for you to confirm whether the app is now working? I have made fixes and updates

**Comment by quadrismegistus** [comment]
You can install now via:

```
pip install prosodic
```

**Comment by sylveawong** [comment]
it works!! i am so excited to play with this – thanks so much!
