### ISSUE TITLE
Prosodic not working properly on Debian

### ISSUE THREAD

**Issue by davidvontamar** [quadrismegistus/prosodic#63]
I'm running Prosodic on Debian Sid with the latest packages. So far it was working very well, until today.
One message that appears many times in yellow in the terminal is:
```
cannot connect to redis. defaulting to json cache
```
The app is very slow and it takes it several minutes to respond to the initial sonnet once launching the web UI.
I really need Prosodic. It helps me a lot. Is this a local issue that I can fix? I'm not sure where Prosodic connects to.

**Comment by quadrismegistus** [comment]
Hi there, I'll look into this, but in the meantime you might check out http://prosodic.stanford.edu/, which is running v1 of Prosodic, in case that holds you over for now

**Comment by quadrismegistus** [comment]
Hi there, would it be possible for you to confirm whether the app is now working? I have made fixes and updates

**Comment by davidvontamar** [comment]
Hello Ryan,

I can confirm that I installed the current version on my up-to-date Debian Sid computer and Prosodic worked in the command line. I tested Prosodic with the verse line "Double double toil and trouble," and the parse command worked as expected.

However, I must report two other issues that I encountered:

1. Using `pipx` on Debian Sid, I had to divert it to Python 3.11 from Python 3.12, because under Python 3.12, there was an error recognizing `imp`. Apparently, it was changed into something else starting from Python 3.12.
2. Yet, running Prosodic under Python 3.11 with the command `prosodic web` fails as well because of an internal error in `prosodic.py` that says:
```
File "[...]/prosodic.py", line 159, in start_interactive_mode
    while(text!="/exit"):
          ^^^^
UnboundLocalError: cannot access local variable 'text' where it is not associated with a value
```
(I shortened the full path)

In any case, I'm relying heavily on the online Prosodic at Stanford with the link that you gave me since then, as it's most practical. I also spread word about Prosodic among my fellow students at the English department at Tel Aviv University, hoping that they will embrace meter in poetry like I do. Prosodic is incredibly helpful. The online Standford version is what I recommend to my friends, since the installation process and the command line usage somewhat intimidates them.

**Comment by quadrismegistus** [comment]
I think that's the older version of prosodic. Could you try pip-installing from github?

```
pip install git+https://github.com/quadrismegistus/prosodic
```

I'll update pypi shortly once I'm a bit more confident this new version works.

**Comment by davidvontamar** [comment]
You are right, Ryan. I re-installed Prosodic from the repository and Prosodic version `2.0.0.dev1` is now present on my computer and works with the web interface, parsing everything correctly.

**Comment by quadrismegistus** [comment]
Great!

I've just updated pypi so you should now be able to install via pip normally as

   pip install prosodic
