### ISSUE TITLE
Python 3 version

### ISSUE THREAD

**Issue by meshgi** [quadrismegistus/prosodic#7]
This library is so cool but it would be even cooler to have a python 3 version of that + possible interfaces. As in another issue mentioned it can be hacked by input/output functions, but I have difficulties in using it under python 3 and 2to3 doesn't seem to work well on this.

I wonder if there is any plan to port into Python 3?

**Comment by andronovhopf** [comment]
Yes please another vote from me for a python 3 version

**Comment by quadrismegistus** [comment]
Thanks guys for dropping in to mention this! I am super busy at the moment with my dissertation and job market and etc but I will try to do this in the next month or two. Thanks again!

**Comment by chrisdonahue** [comment]
Thanks for doing the upgrade! I am using the Python 3 version. Any chance the pip package could be upgraded to support Python 3 at some point? Or can you include the `setup.py` in the repository so I can install it locally with pip?

**Comment by quadrismegistus** [comment]
I think this should now be solved in the latest update: python3 and pypi conversions complete?
