### ISSUE TITLE
loadConfigPy is not defined.

### ISSUE THREAD

**Issue by asmplease** [quadrismegistus/prosodic#8]
I am using python27 to run the program. 
I am facing the following issue
File "prosodic.py", line 23, in <module>
    config=loadConfigPy(toprint=toprintconfig,dir_prosodic=dir_prosodic)
NameError: name 'loadConfigPy' is not defined

**Comment by quadrismegistus** [comment]
Hm, I can't replicate this. loadConfigPy is coming from line 22 ("from tools import *"), stored in lib/tools.py. Do you have a tools.py in your working directory, or is there any way that "tools" here could refer to a different file/module?

**Comment by quadrismegistus** [comment]
I believe this is fixed
